module "jwdb_rds" {
  source = "github.com/ryno75/tf_aws_rds"
  // source = "github.com/terraform-community-modules/tf_aws_rds"
  rds_instance_name = "${var.rds_instance_name}"
  rds_instance_class = "${var.rds_instance_type}"
  rds_engine_type = "${var.rds_engine}"
  db_parameter_group = "${var.rds_parameter_group}"
  rds_engine_version = "${var.rds_engine_version}"
  rds_allocated_storage = "${var.rds_allocated_storage}"
  rds_storage_type = "${var.rds_storage_type}"
  rds_security_group_id = "${aws_security_group.sg_rds.id}"
  rds_is_multi_az = "${var.rds_multi_az}"
  subnet_az1 = "${element(split(",",module.vpc.public_subnets),0)}"
  subnet_az2 = "${element(split(",",module.vpc.public_subnets),1)}"
  database_name = "${var.database_name}"
  database_user = "${var.database_username}"
  database_password = "${var.database_password}"
  aws_access_key = "${var.aws_access_key}"
  aws_secret_key = "${var.aws_secret_key}"
  aws_region = "${var.aws_region}"
}
